[package]
name = "tremaux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delegate = "0.9.0"
derive_more = "0.99.17"
graph = "0.3.0"
